security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\UserApp
                property: email # Symfony bech ylawej bel email fel login

    firewalls:
            main:
                lazy: true
                provider: app_user_provider
                
                # Hadhi el line elli t'salla7 el mochkla:
                entry_point: App\Security\LoginManagerAuthenticator
                
                custom_authenticator: App\Security\LoginManagerAuthenticator
                
                logout:
                    path: app_logout
                    target: app_login

                remember_me:
                    secret: '%kernel.secret%'
                    lifetime: 604800
                    path: /
                # by default, the feature is enabled by checking a checkbox in the
                # login form, uncomment the following line to always enable it.
                #always_remember_me: true