# config/services.yaml

parameters:
    # dossier pour uploader les images des activités
    upload_dir: 'C:/wamp64/www/uploads'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'